### PR TITLE
Complex visual objects

### LINKED ISSUE #36: Allowing arbitrarily complex visual stimuli
ACT-R allows you to add arbitrarily complex visual stimuli to the visicon (see e.g. [examples here](https://github.com/asmaloney/ACT-R/blob/main/examples/vision-module/new_visicon_features.py)). You can, for instance, create an object with attributes like `shape`, `texture`, `rotation` and so on. Because of this data structure, arbitrary attributes of visual objects can be directly stored and queried in various buffers, while comprehenders scan and compare an array of objects.

At the moment, pyactr is more strict: the currently implemented visual module requires all objects to be the special chunktype `_visuallocation`, which has only attributes of location, color, and value. The code below results in the error `You cannot redefine slots of the chunk type '_visuallocation'; you can only use the slots 'screen_x, screen_y, color, value'`. (It seems like it actually allows writing the stimulus with its `shape` attribute to the environment, but fails when trying to bring it into the visual_location buffer). 

```python
import pyactr as actr

env = actr.Environment(focus_position=(0, 0))
model = actr.ACTRModel(
    environment=env,
    automatic_visual_search=True,
    motor_prepared=True,
    strict_harvesting=False,
    emma=False
)

dm = model.decmem

model.set_goal(name="imaginal", delay=0.2)

model.visualBuffer("visual", "visual_location", default_harvest=dm, finst=4)

model.productionstring(name="encodeVisual", string="""
    =visual_location>
        isa _visuallocation
==>
    +visual>
        isa _visual
        cmd         move_attention
        screen_pos  =visual_location
    ~visual_location>
""")

stimulus = {0: {'position': (100,100), 'shape': 'triangle'}}

sim = model.simulation(realtime=False,
                       gui=False,
                       environment_process=env.environment_process,
                       stimuli=stimulus,
                       triggers='',
                       times=100
                       )
sim.run()
```

As far as I can tell, there's currently no way around this, by e.g. predefining stimuli as part of an inheriting chunktype with more attributes.

This is important for my particular usecase at the moment, so I'll be working to build in an option to extend _visuallocation and _visual chunks, and will link a PR when it's working.

### PR DESCRIPTION
**Pull request by j-duff**
Adds support for arbitrarily complex visual stimuli, resolves #36.

I prepared the visual system to deal with stimulus dictionaries with keys specifying extended chunktypes (`'visual_location_chunktype'` and `'visual_chunktype'`) for the objects those stimuli will create in the visual buffers. To do this, I added a helper function `chunk_from_stimulus()` in vision.py, which handles the creation of a chunk using these keys in the stimulus dictionary, as well as an additional key `'hidden'` which is expected to bear a list of keys which should be ignored when creating chunks in the `visual_location` buffer (in addition to `'text'`, which has this behavior as default). This helper function is now called in the four methods that create visual chunks from the environment: `VisualLocation.find()`, `VisualLocation.automatic_search()`, `Visual.automatic_buffering()`, and `Visual.shift()`. It doesn't change the behavior of standard visual functions in the absence of the special stimulus keys, and passes the unit tests.

In the process, I also:
- added support for defining chunktypes as extensions of an ancestor, as an `include` parameter to the `chunktype()` function, which takes the name of an existing chunktype and includes all the existing chunktype's attributes in the new chunktype, mirroring the behavior of `:include` in Lisp ACT-R
- corrected a bug that meant the built-in 'color' attributes were also usually not getting copied over into the Visual Buffer

Here's a sample model and corresponding trace to demonstrate the intended functionality:

```python
import pyactr as actr

env = actr.Environment(focus_position=(0, 0))
model = actr.ACTRModel(
    environment=env,
    automatic_visual_search=True,
    motor_prepared=True,
    strict_harvesting=False,
    emma=False
)

actr.chunktype("shape", ('shape', 'texture'), include='_visual')

dm = model.decmem
model.set_goal(name="imaginal", delay=0.2)
model.visualBuffer("visual", "visual_location", default_harvest=dm, finst=4)

model.productionstring(name="encodeVisual", string="""
    =visual_location>
        isa _visuallocation
==>
    +visual>
        isa _visual
        cmd         move_attention
        screen_pos  =visual_location
    ~visual_location>
""")

stimulus = {0: {'position': (100,100),
                'shape': 'triangle',
                'texture': 'striped',
                'color': 'gold',
                'visual_typename': 'shape',
                'hidden': ['shape', 'texture']}}

sim = model.simulation(realtime=False,
                       gui=False,
                       environment_process=env.environment_process,
                       stimuli=stimulus,
                       triggers='',
                       times=100
                       )
sim.run()
```

```
(0, 'PROCEDURAL', 'CONFLICT RESOLUTION')
(0, 'PROCEDURAL', 'NO RULE FOUND')
****Environment: {0: {'position': (100, 100), 'shape': 'triangle', 'texture': 'striped', 'color': 'gold', 'visual_typename': 'shape', 'hidden': ['shape', 'texture']}}
(0, 'visual_location', 'ENCODED LOCATION: _visuallocation(color= gold, screen_x= 100, screen_y= 100, value= )')
(0, 'PROCEDURAL', 'CONFLICT RESOLUTION')
(0, 'PROCEDURAL', 'RULE SELECTED: encodeVisual')
(0.05, 'PROCEDURAL', 'RULE FIRED: encodeVisual')
(0.05, 'visual_location', 'CLEARED')
(0.05, 'visual', 'PREPARATION TO SHIFT VISUAL ATTENTION STARTED')
(0.05, 'visual', 'PREPARATION TO SHIFT VISUAL ATTENTION COMPLETED')
(0.05, 'PROCEDURAL', 'CONFLICT RESOLUTION')
(0.05, 'PROCEDURAL', 'NO RULE FOUND')
(0.135, 'visual', 'CLEARED')
(0.135, 'visual', "ENCODED VIS OBJECT:'shape(cmd= move_attention, color= gold, screen_pos= _visuallocation(color= gold, screen_x= 100, screen_y= 100, value= ), shape= triangle, texture= striped, value= )'")
(0.135, 'visual', 'SHIFT COMPLETE TO POSITION: [100, 100]')
(0.135, 'PROCEDURAL', 'CONFLICT RESOLUTION')
(0.135, 'PROCEDURAL', 'NO RULE FOUND')
```

### CODE REVIEW

**Comment by j-duff** [comment]
Just noting one thing about usage: Chunks for visual objects must subsume the request to the visual_location buffer in order to match (see visual.py line 202, matches are returned only `if visible_chunk <= chunk_used_for_search`). As a result, stimuli with extra visual attributes that are not hidden from the visual_location buffer (e.g. maybe `'width'` or something) will not match any request that does not specify that value. I think perhaps the default behavior for stimuli should be to hide ALL extra visual attributes from visual_location? Otherwise, maybe the requirement for subsumption can be removed.

**Comment by j-duff** [comment]
Ah, I didn't check the tutorials. I'm getting the same tkinter errors, probably some incompatibility I didn't realize between my few adjustments to the environment code and the GUI implementation. Thanks, will investigate further!

**Comment by asmaloney** [comment]
> added support for defining chunktypes as extensions of an ancestor

ACT-R allows inheriting from multiple chunks:

> When creating chunk-types they may be organized into a hierarchy, with new chunk-types inheriting slots from one or more parent chunk-types. (pg. 80)

Example from docs:

```
(chunk-type goal slot1 state)
(chunk-type-fct '(other-type slot1 slot2))
(chunk-type-fct '((subgoal2 (:include goal) (:include other-type))))
```

which results in:
```
SUBGOAL2 <- GOAL, OTHER-TYPE
   SLOT2
   SLOT1
   STATE
```

Should your include param be a list?

**Comment by j-duff** [comment]
Ok, I corrected the tkinter error. It was a case of accidental deep copying that added unexpected keys like `'cmd'` and `'value'` to the stimulus dictionaries in the environment. I'll note that any non-text visual objects like the ones I'm using here won't work with the GUI, and will cause similar errors. Maybe someday there can be support for drawing shapes and things, but for now my intended goal was just to allow the models themselves to interface with objects of arbitrary complexity.

Thank you @asmaloney for catching the possibility of multiple ancestors, I adjusted `actr.chunktype()` to now take either a single string naming a chunktype, as before, or a list of chunktype names. See implementation below.

I have also adjusted the UI for specifying which attributes are encoded in `visual_location`. The original pyactr behavior was that only `'screen_x'` and `'screen_y'` were ever usable in `visual_location` searches or copied over into the buffer. In my first version above, the modeler could specify a `'hidden'` key in their stimuli that marked any custom attributes that should not be present in `visual_location`. Given that non-location attributes present in `visual_location` significantly alter visual search performance (see my comment above), I decided to switch the burden of specification so that now, only `'screen_x'` and `'screen_y'` will ever be visible to `visual_location`, hiding all novel custom attributes, unless the user specifies further attributes in an optional `'externally_visible'` key in their stimulus. There's a comment noting this in the definition of the helper function `chunk_from_stimulus()` in vision.py.

The current branch passes all tests and returns no errors on the tutorials.

Updated sample model and trace below.


```{python}
import pyactr as actr

env = actr.Environment(focus_position=(0, 0))
model = actr.ACTRModel(
    environment=env,
    automatic_visual_search=True,
    motor_prepared=True,
    strict_harvesting=False,
    emma=False
)

actr.chunktype("field", ("texture", "color"))
actr.chunktype("shape", ("shape", "rotation"), include=['_visual', 'field'])

dm = model.decmem
model.set_goal(name="imaginal", delay=0.2)
model.visualBuffer("visual", "visual_location", default_harvest=dm, finst=4)

model.productionstring(name="encodeVisual", string="""
    =visual_location>
        isa _visuallocation
==>
    +visual>
        isa         shape
        cmd         move_attention
        screen_pos  =visual_location
    ~visual_location>
""")

stimulus = {0: {'position': (100,100),
                'shape': 'triangle',
                'texture': 'striped',
                'color': 'gold',
                'visual_typename': 'shape'}}

sim = model.simulation(realtime=False,
                       gui=False,
                       environment_process=env.environment_process,
                       stimuli=stimulus,
                       triggers='',
                       times=100
                       )
sim.run()
```

```
(0, 'PROCEDURAL', 'CONFLICT RESOLUTION')
(0, 'PROCEDURAL', 'NO RULE FOUND')
****Environment: {0: {'position': (100, 100), 'shape': 'triangle', 'texture': 'striped', 'color': 'gold', 'visual_typename': 'shape'}}
(0, 'visual_location', 'ENCODED LOCATION: _visuallocation(color= , screen_x= 100, screen_y= 100, value= )')
(0, 'PROCEDURAL', 'CONFLICT RESOLUTION')
(0, 'PROCEDURAL', 'RULE SELECTED: encodeVisual')
(0.05, 'PROCEDURAL', 'RULE FIRED: encodeVisual')
(0.05, 'visual_location', 'CLEARED')
(0.05, 'visual', 'PREPARATION TO SHIFT VISUAL ATTENTION STARTED')
(0.05, 'visual', 'PREPARATION TO SHIFT VISUAL ATTENTION COMPLETED')
(0.05, 'PROCEDURAL', 'CONFLICT RESOLUTION')
(0.05, 'PROCEDURAL', 'NO RULE FOUND')
(0.135, 'visual', 'CLEARED')
(0.135, 'visual', "ENCODED VIS OBJECT:'shape(cmd= move_attention, color= gold, rotation= , screen_pos= _visuallocation(color= , screen_x= 100, screen_y= 100, value= ), shape= triangle, texture= striped, value= )'")
(0.135, 'visual', 'SHIFT COMPLETE TO POSITION: [100, 100]')
(0.135, 'PROCEDURAL', 'CONFLICT RESOLUTION')
(0.135, 'PROCEDURAL', 'NO RULE FOUND')
```

**Comment by jakdot** [comment]
Hi, Thanks Jack, I am just going through your code. I think I can merge it but before that, I have a few things:

1. In chunk_from_stimulus, you call one argument "buffer". "buffer" is a dedicated keyword in Python - could you change it to for example buffer_name in that function?

2. In the docstring to chunk_from_stimulus, you talk about flags. I don't see flags anywhere in that function - am I missing something?

3. I think we can remove the class attribute _VISUAL from the class Visual, no? It was used in creating chunks inside that class, but now that this is delegated to the separate function chunks_from_stimulus, I don't see why it is needed.

4. I am wondering about that include option in chunks. I like it but is there a reason that it precedes defaults? I don't use defaults, but maybe other people do, and if they don't specify the argument name, it might break their code. Would it be equally fine to let include appear after defaults?

**Comment by j-duff** [comment]
Thanks, all of these seem like good suggestions to me, and all have been implemented. Re: (2), that was indeed an oversight from an earlier version of the function, I corrected and simplified that docstring. And Re: (4), I don't see any reason not to have it the other way, and I hadn't caught that it might break people's code. Fixed accordingly.

**Comment by jakdot** [comment]
Thanks a lot @j-duff ! I merged it.

> Maybe someday there can be support for drawing shapes and things, but for now my intended goal was just to allow the models themselves to interface with objects of arbitrary complexity.

If at some day you get to implementing support for shapes and lines with GUI, I think that would be a nice feature. It's present in the Lisp version so we could get inspiration from their implementation.

**Pull request merged**
